### PR TITLE
Fix exp! fallback on Translation group

### LINKED ISSUE #483: DomainError with ExponentialRetraction with `mean` of SE2
Hi, I'm upgrading code to v0.8 and get a DomainError, here is a minimum example:
```julia
julia> using Manifolds

julia> p1 = ProductRepr([0.0,0.0], [1.0 0.0; 0.0 1.0])
ProductRepr with 2 submanifold components:
 Component 1 =
  2-element Vector{Float64}:
   0.0
   0.0
 Component 2 =
  2×2 Matrix{Float64}:
   1.0  0.0
   0.0  1.0

julia> p2 = ProductRepr([0.0,0.0], [0.0 -1.0; 1.0 0.0])
ProductRepr with 2 submanifold components:
 Component 1 =
  2-element Vector{Float64}:
   0.0
   0.0
 Component 2 =
  2×2 Matrix{Float64}:
   0.0  -1.0
   1.0   0.0

julia> M = SpecialEuclidean(2)
SpecialEuclidean(2)

julia> mean(M, [p1,p2])
ERROR: DomainError with ExponentialRetraction():
You can not use the exponential map as an inner method to solve the ode for the exponential map.
Stacktrace:
  [1] ODEExponentialRetraction(r::ExponentialRetraction, #unused#::DefaultOrthonormalBasis{ℝ, ManifoldsBase.TangentSpaceType})
    @ ManifoldsBase ~/.julia/packages/ManifoldsBase/L10sL/src/retractions.jl:93
  [2] ODEExponentialRetraction(r::ExponentialRetraction)
    @ ManifoldsBase ~/.julia/packages/ManifoldsBase/L10sL/src/retractions.jl:82
  [3] exp!(#unused#::ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.TraitList{HasBiinvariantMetric, ManifoldsBase.TraitList{HasLeftInvariantMetric, ManifoldsBase.TraitList{HasRightInvariantMetric, ManifoldsBase.TraitList{IsDefaultMetric{EuclideanMetric}, ManifoldsBase.TraitList{IsMetricManifold, ManifoldsBase.TraitList{IsDefaultConnection{LeviCivitaConnection}, ManifoldsBase.TraitList{IsConnectionManifold, ManifoldsBase.TraitList{ManifoldsBase.IsExplicitDecorator, ManifoldsBase.EmptyTrait}}}}}}}}}, M::TranslationGroup{Tuple{2}, ℝ}, q::Vector{Float64}, p::Vector{Float64}, X::Vector{Float64})
    @ Manifolds ~/.julia/packages/Manifolds/wpEil/src/manifolds/MetricManifold.jl:257
  [4] exp! (repeats 2 times)
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:282 [inlined]
  [5] exp!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:275 [inlined]
  [6] map
    @ ./tuple.jl:266 [inlined]
  [7] exp!(M::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, q::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, p::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, X::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}})
    @ Manifolds ~/.julia/packages/Manifolds/wpEil/src/manifolds/ProductManifold.jl:394
  [8] _retract!(M::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, q::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, p::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, X::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, #unused#::ExponentialRetraction)
    @ ManifoldsBase ~/.julia/packages/ManifoldsBase/L10sL/src/retractions.jl:636
  [9] retract!(M::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, q::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, p::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, X::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, m::ExponentialRetraction)
    @ ManifoldsBase ~/.julia/packages/ManifoldsBase/L10sL/src/retractions.jl:619
 [10] retract!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:308 [inlined]
 [11] retract! (repeats 2 times)
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:282 [inlined]
 [12] retract!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:275 [inlined]
 [13] retract!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:291 [inlined]
 [14] retract! (repeats 3 times)
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:282 [inlined]
 [15] retract!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/nested_trait.jl:275 [inlined]
 [16] retract!
    @ ~/.julia/packages/ManifoldsBase/L10sL/src/retractions.jl:629 [inlined]
 [17] mean!(M::GroupManifold{ℝ, ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, Manifolds.SemidirectProductOperation{RotationAction{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}, LeftAction}}}, y::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, x::Vector{ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}}, w::StatsBase.UnitWeights{Float64}, ::GradientDescentEstimation; p0::ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}, stop_iter::Int64, retraction::ExponentialRetraction, inverse_retraction::LogarithmicInverseRetraction, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Manifolds ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:387
 [18] mean!
    @ ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:365 [inlined]
 [19] #mean!#146
    @ ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:349 [inlined]
 [20] mean!
    @ ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:348 [inlined]
 [21] #mean#144
    @ ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:308 [inlined]
 [22] mean(M::GroupManifold{ℝ, ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, Manifolds.SemidirectProductOperation{RotationAction{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}, LeftAction}}}, x::Vector{ProductRepr{Tuple{Vector{Float64}, Matrix{Float64}}}}, method::GradientDescentEstimation) (repeats 2 times)
    @ Manifolds ~/.julia/packages/Manifolds/wpEil/src/statistics.jl:307
 [23] top-level scope
    @ REPL[11]:1
```

### PR DESCRIPTION
**Pull request by kellertuer**
To not fall back to the ODE solver (just because Euclidean is a `MetricManifold` but the ExplicitDecorator comes later).
Fixes #483.

The one thing to discuss here is, whether this should be done for all group manifolds (i.e. to have a special just-fallback-exp!)?
What do you think @mateuszbaran ?

### CODE REVIEW

**Comment by mateuszbaran** [comment]
I think we should instead use the (more or less) same traits as SO(n):
```julia
@inline function active_traits(f, ::SpecialOrthogonal, args...)
    if is_metric_function(f)
        #pass to Rotations by default - but keep Group Decorator for the retraction
        return merge_traits(
            IsGroupManifold(MultiplicationOperation()),
            IsExplicitDecorator(),
        )
    else
        return merge_traits(
            IsGroupManifold(MultiplicationOperation()),
            HasBiinvariantMetric(),
            IsDefaultMetric(EuclideanMetric()),
            IsExplicitDecorator(), #pass to Rotations by default/last fallback
        )
    end
end
```
Metric functions should quickly fall into the `IsExplicitDecorator()` case.

File: src/groups/translation_group.jl [hunk 1]
```diff
@@ -19,13 +19,18 @@ function TranslationGroup(n::Int...; field::AbstractNumbers=ℝ)
...
 @inline function active_traits(f, M::TranslationGroup, args...)
-    return merge_traits(
-        IsGroupManifold(M.op),
-        IsDefaultMetric(EuclideanMetric()),
-        HasBiinvariantMetric(),
-        active_traits(f, M.manifold, args...),
-        IsExplicitDecorator(),
-    )
+    if is_metric_function(f)
+        #pass to Rotations by default - but keep Group Decorator for the retraction
```
Comment (mateuszbaran) [inline src/groups/translation_group.jl:23]:
```suggestion
        #pass to Euclidean by default - but keep Group Decorator for the retraction
```

File: src/groups/translation_group.jl [hunk 2]
```diff
@@ -19,13 +19,18 @@ function TranslationGroup(n::Int...; field::AbstractNumbers=ℝ)
...
+        return merge_traits(IsGroupManifold(M.op), IsExplicitDecorator())
+    else
+        return merge_traits(
+            IsGroupManifold(M.op),
+            HasBiinvariantMetric(),
+            IsDefaultMetric(EuclideanMetric()),
+            active_traits(f, M.manifold, args...),
+            IsExplicitDecorator(), #pass to Rotations by default/last fallback
```
Comment (mateuszbaran) [inline src/groups/translation_group.jl:31]:
```suggestion
            IsExplicitDecorator(), #pass to Euclidean by default/last fallback
```

**Review by mateuszbaran — APPROVED** [review]
