### PR TITLE
Fix #518

### LINKED ISSUE #518: MethodError: no method matching _inverse_retract!(::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ} ...
Hi, It looks like the latest release of Manifolds broke CI in RoME and IncrementalInference. 
I get this new error from github CI

```julia
MethodError: no method matching _inverse_retract!(::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, ::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, ::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, ::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, ::Manifolds.InverseProductRetraction{Tuple{ManifoldsBase.LogarithmicInverseRetraction, ManifoldsBase.LogarithmicInverseRetraction}})
  Closest candidates are:
    _inverse_retract!(::AbstractManifold, ::Any, ::Any, ::Any, ::ManifoldsBase.LogarithmicInverseRetraction) at /home/runner/.julia/packages/ManifoldsBase/YRaAP/src/retractions.jl:324
    _inverse_retract!(::AbstractManifold, ::Any, ::Any, ::Any, ::ManifoldsBase.CayleyInverseRetraction) at /home/runner/.julia/packages/ManifoldsBase/YRaAP/src/retractions.jl:330
    _inverse_retract!(::AbstractManifold, ::Any, ::Any, ::Any, ::ManifoldsBase.EmbeddedInverseRetraction) at /home/runner/.julia/packages/ManifoldsBase/YRaAP/src/retractions.jl:333
    ...
  Stacktrace:
    [1] inverse_retract!(M::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, X::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, p::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, q::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, m::Manifolds.InverseProductRetraction{Tuple{ManifoldsBase.LogarithmicInverseRetraction, ManifoldsBase.LogarithmicInverseRetraction}})
      @ ManifoldsBase ~/.julia/packages/ManifoldsBase/YRaAP/src/retractions.jl:322
    [2] inverse_retract!
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:308 [inlined]
    [3] inverse_retract! (repeats 2 times)
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:282 [inlined]
    [4] inverse_retract!
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:275 [inlined]
    [5] mean!(M::ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, y::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, x::Vector{ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}}, w::StatsBase.UnitWeights{Float64}, ::Manifolds.GradientDescentEstimation; p0::ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}, stop_iter::Int64, retraction::Manifolds.ProductRetraction{Tuple{ManifoldsBase.ExponentialRetraction, ManifoldsBase.ExponentialRetraction}}, inverse_retraction::Manifolds.InverseProductRetraction{Tuple{ManifoldsBase.LogarithmicInverseRetraction, ManifoldsBase.LogarithmicInverseRetraction}}, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ Manifolds ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:383
    [6] mean!
      @ ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:[367](https://github.com/JuliaRobotics/RoME.jl/runs/7697467681?check_suite_focus=true#step:7:370) [inlined]
    [7] #mean!#145
      @ ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:351 [inlined]
    [8] mean!
      @ ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:350 [inlined]
    [9] #mean#143
      @ ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:310 [inlined]
   [10] mean (repeats 2 times)
      @ ~/.julia/packages/Manifolds/CqWuP/src/statistics.jl:309 [inlined]
   [11] mean
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:308 [inlined]
   [12] mean (repeats 2 times)
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:282 [inlined]
   [13] mean
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:275 [inlined]
   [14] mean
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:291 [inlined]
   [15] mean(t::ManifoldsBase.TraitList{Manifolds.IsGroupManifold{Manifolds.SemidirectProductOperation{Manifolds.RotationAction{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}, Manifolds.LeftAction}}}, ManifoldsBase.TraitList{ManifoldsBase.IsExplicitDecorator, ManifoldsBase.EmptyTrait}}, M::Manifolds.GroupManifold{ℝ, ProductManifold{ℝ, Tuple{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}}}, Manifolds.SemidirectProductOperation{Manifolds.RotationAction{TranslationGroup{Tuple{2}, ℝ}, SpecialOrthogonal{2}, Manifolds.LeftAction}}}, x::Vector{ArrayPartition{Float64, Tuple{Vector{Float64}, Matrix{Float64}}}})
      @ Manifolds ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:282
   [16] mean
      @ ~/.julia/packages/ManifoldsBase/YRaAP/src/nested_trait.jl:275 [inlined]
   [17] mean
      @ ~/.julia/packages/ApproxManifoldProducts/igkT4/src/services/ManifoldKernelDensity.jl:96 [inlined]
   [18] calcMean (repeats 2 times)
      @ ~/.julia/packages/ApproxManifoldProducts/igkT4/src/services/ManifoldKernelDensity.jl:104 [inlined]
   [19] calcPPE(var::DFGVariable{Pose2}, varType::Pose2; ppeType::Type{MeanMaxPPE}, solveKey::Symbol, ppeKey::Symbol, timestamp::Dates.DateTime)
      @ IncrementalInference ~/.julia/packages/IncrementalInference/cF5DM/src/FGOSUtils.jl:242
   [20] setPPE!(subfg::GraphsDFG{SolverParams, DFGVariable, DFGFactor}, label::Symbol, solveKey::Symbol, ppeType::Type{MeanMaxPPE}, newPPEVal::Nothing)
      @ IncrementalInference ~/.julia/packages/IncrementalInference/cF5DM/src/FGOSUtils.jl:577
   [21] setPPE!
      @ ~/.julia/packages/IncrementalInference/cF5DM/src/FGOSUtils.jl:575 [inlined]
   [22] doautoinit!(dfg::GraphsDFG{SolverParams, DFGVariable, DFGFactor}, xi::DFGVariable{Pose2}; solveKey::Symbol, singles::Bool, N::Int64, logger::Logging.ConsoleLogger)
      @ IncrementalInference ~/.julia/packages/IncrementalInference/cF5DM/src/services/GraphInit.jl:132
   [23] #doautoinit!#29
      @ ~/.julia/packages/IncrementalInference/cF5DM/src/services/GraphInit.jl:160 [inlined]
   [24] addFactor!(dfg::GraphsDFG{SolverParams, DFGVariable, DFGFactor}, Xi::Vector{DFGVariable{Pose2}}, usrfnc::Pose2Pose2{DiagNormal}; multihypo::Vector{Float64}, nullhypo::Float64, solvable::Int64, tags::Vector{Symbol}, timestamp::TimeZones.ZonedDateTime, graphinit::Bool, threadmodel::Type, suppressChecks::Bool, inflation::Float64, namestring::Symbol, _blockRecursion::Bool)
      @ IncrementalInference ~/.julia/packages/IncrementalInference/cF5DM/src/FactorGraph.jl:691
   [25] addFactor!(dfg::GraphsDFG{SolverParams, DFGVariable, DFGFactor}, xisyms::Vector{Symbol}, usrfnc::Pose2Pose2{DiagNormal}; suppressChecks::Bool, kw::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
      @ IncrementalInference ~/.julia/packages/IncrementalInference/cF5DM/src/FactorGraph.jl:717
   [26] addFactor!
      @ ~/.julia/packages/IncrementalInference/cF5DM/src/FactorGraph.jl:711 [inlined]
   [27] macro expansion
      @ ~/work/RoME.jl/RoME.jl/test/testParametric.jl:28 [inlined]
   [28] macro expansion
      @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Test/src/Test.jl:1151 [inlined]
   [29] top-level scope
      @ ~/work/RoME.jl/RoME.jl/test/testParametric.jl:17
   [30] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [31] top-level scope
      @ ~/work/RoME.jl/RoME.jl/test/runtests.jl:79
   [32] include(fname::String)
      @ Base.MainInclude ./client.jl:444
   [33] top-level scope
      @ none:6
   [34] eval
      @ ./boot.jl:360 [inlined]
   [35] exec_options(opts::Base.JLOptions)
      @ Base ./client.jl:261
   [36] _start()
      @ Base ./client.jl:485
```

### PR DESCRIPTION
**Pull request by mateuszbaran**

### CODE REVIEW

File: src/manifolds/ProductManifold.jl [hunk 1]
```diff
@@ -736,6 +736,23 @@ for TP in [ProductRepr, ArrayPartition]
                     ),
                 )
             end
+            function inverse_retract!(
```
Comment (kellertuer) [inline src/manifolds/ProductManifold.jl:739]: oh, did we forget to implement the mutating inverse retraction for product manifolds? Interesting!

**Review by kellertuer — APPROVED** [review]

File: src/manifolds/ProductManifold.jl (hunk 1 above)
Comment (mateuszbaran) [reply src/manifolds/ProductManifold.jl:739]: Yes, I was very surprised that we didn't have that.

Comment (kellertuer) [reply src/manifolds/ProductManifold.jl:739]: So am I, good that we have it now, then :)
